### ISSUE TITLE
Error when running some git repo

### ISSUE THREAD

**Issue by kjhyoo** [MetricsGrimoire/CVSAnalY#11]
Hi,

When I tried to analyze a git repository, I faced the following error.

---

Parsing log for webkit-efl/ (git)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/DBTempLog.py", line 140, in __writer
    cursor.executemany (statement ("INSERT into _temp_log (rev, date, object) values (?, ?, ?)", self.db.place_holder), commits)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 223, in executemany
    r = self._query('\n'.join([query[:p], ',\n'.join(q), query[e:]]))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 316, in _query
    rowcount = self._do_query(q)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 280, in _do_query
    db.query(q)
OperationalError: (2006, 'MySQL server has gone away')

---

How can I analyze? (I used the latest version of CVSAnalY2 and other repositories are analyzed and fine.)
Git URL : review.tizen.org/framework/web/webkit-efl.git

**Comment by sduenas** [comment]
That's an error from your MySQL server. Probably CVSAnalY lasts too long analyzing the log and there's no interaction with your server. MySQL waits for some time and if it has not received any data from the client, it closes the connection. You can configure your connection time out value setting **wait_timeout** variable in _/etc/mysql/my.cnf_. The value is in seconds.

More info in http://dev.mysql.com/doc/refman/5.0/en/gone-away.html

**Comment by kjhyoo** [comment]
Thank you for your help!
Finally, I've analyzed.

I changed mysql setting (/etc/mysql/my.cnf )
max_allowed_packet      = 64M (In the past value, 16M)
