### ISSUE TITLE
2 Errors when running CVSAnalY

### ISSUE THREAD

**Issue by kjhyoo** [MetricsGrimoire/CVSAnalY#13]
I need your help...
- for GIT

Git URL : review.tizen.org/framework/uifw/elementary.git

---

Parsing log for framework/uifw/elementary (git)
Traceback (most recent call last):
  File "/usr/local/bin/cvsanaly2", line 5, in <module>
    pkg_resources.run_script('cvsanaly2==2.1.0', 'cvsanaly2')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/EGG-INFO/scripts/cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/main.py", line 328, in main
    reader.start (new_line, (parser, writer))
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/Log.py", line 92, in start
    self._read_from_repository (new_line_cb, user_data)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/Log.py", line 78, in _read_from_repository
    new_line_cb (line, user_data)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/main.py", line 320, in new_line
    parser.feed (line)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/Parser.py", line 56, in feed
    self._parse_line (line)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/GitParser.py", line 202, in _parse_line
    self.branch.set_tail (git_commit)
AttributeError: 'NoneType' object has no attribute 'set_tail'

---
- for SVN

SVN UTL : http://svn.enlightenment.org/svn/e/trunk

---

Parsing log for http://svn.enlightenment.org/svn/e/trunk (svn)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/Log.py", line 62, in _logreader
    repo.log (self.uri or repo.get_uri ())
  File "/usr/local/lib/python2.7/dist-packages/repositoryhandler/backends/svn.py", line 278, in log
    self._run_command(command, LOG)
  File "/usr/local/lib/python2.7/dist-packages/repositoryhandler/backends/svn.py", line 133, in _run_command
    Repository._run_command(self, command, type, input)
  File "/usr/local/lib/python2.7/dist-packages/repositoryhandler/backends/__init**.py", line 168, in _run_command
    raise RepositoryCommandError(e.cmd, e.returncode, e.error)
RepositoryCommandError: Command '['svn', '-v', 'log', 'http://svn.enlightenment.org/svn/e/trunk']' returned non-zero exit status 1

---

**Comment by dicortazar** [comment]
Hello kjhyoo,

Thanks for your bug report!

Please, could you specify the exact git clone command you have used for cloning the repository?.

I've tried git clone git://review.tizen.org/framework/uifw/elementary.git and git clone https://review.tizen.org/framework/uifw/elementary.git, but none of them work.

Regarding to the first one: 

Cloning into 'elementary'...
fatal: The remote end hung up unexpectedly

Regarding to the second one I obtain similar failed results... 

I have also created an account in Tizen just to download using the ssh connection, and this still does not work. (git clone ssh://user@review.tizen.org:29418/)

Any idea?

Regarding to the second one, still in progress the analysis, please give me some minutes more.

Update: I get the same error as yours. I'm trying now to download the repository and later run again CVSAnalY to check if I get the same error (I guess so in any case...)

**Comment by kjhyoo** [comment]
Hi Daniel,

I just followed the Tizen web-site (https://source.tizen.org/documentation/developer-guide/environment-setup),
(You have to sign in https://review.tizen.org/gerrit/ and register you public ssh key)

My ssh config file :

---

Host review.tizen.org
    Hostname review.tizen.org
    IdentityFile ~/.ssh/id_rsa
    User [user]
    Port 29418

---

And this is my git clone command (it's work) :
git clone review.tizen.org:framework/uifw/elementary

**Comment by dicortazar** [comment]
Ok, thanks.

Regarding to the SVN project, I also get the same error even once downloaded. So, my next try is to simply download the svn log (svn -v log) just to check that this is being properly downloaded.

**Comment by dicortazar** [comment]
Hi again,

The command does not work. So regarding to the SVN project, this is not an issue of CVSAnalY, but of the log of the project Enlightenment. My suggestion is to go there and open a bug report  or directly talk with enlightenment developers.

After running the command (I previously downloaded the svn) I get the following error:

$ svn -v log > enlightenment_log.txt

svn: REPORT de '/svn/e/!svn/bc/83038/trunk': Could not read chunk size: connection was closed by server (http://svn.enlightenment.org)

**Comment by andygrunwald** [comment]
Is this issue still up to date or was it fixed in the meantime?

**Comment by andygrunwald** [comment]
Hey @dicortazar and @kjhyoo,
any update on this? 
Is this issue still up to date or was it fixed in the meantime?

**Comment by andygrunwald** [comment]
No update since 20. October 2013.
I will close this issue. If we got more information we will open it again.
