### ISSUE TITLE
Crash while building filepaths

### ISSUE THREAD

**Issue by sduenas** [MetricsGrimoire/CVSAnalY#2]
Running cvsanaly against PETALS repository, we get the next error

```
cvsanaly2 -u root -p root -d petals_cvsanaly --extensions=Metrics --metrics-all https://anonymous:anonymous@svn.petalslink.org/svnroot/trunk/product/dev/prod/petals/`

Traceback (most recent call last):
  File "/usr/local/bin/cvsanaly2", line 5, in <module>
    pkg_resources.run_script('cvsanaly2==2.1.0', 'cvsanaly2')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 499, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1235, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/EGG-INFO/scripts/cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/main.py", line 334, in main
    emg.run_extensions (repo, path or uri, db)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/ExtensionsManager.py", line 84, in run_extensions
    self.run_extension (name, extension, repo, uri, db)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/ExtensionsManager.py", line 56, in run_extension
    extension.run (repo, uri, db)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/extensions/Metrics.py", line 900, in run
    relative_path = fr.get_path ()
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/extensions/FileRevs.py", line 99, in get_path
    relative_path = self.fp.get_path (file_id, commit_id, self.repoid).strip ("/")
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/extensions/FilePaths.py", line 150, in get_path
    path = self.__build_path (file_id, adj)
  File "/usr/local/lib/python2.7/dist-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/extensions/FilePaths.py", line 138, in __build_path
    id = adj.adj[id]
KeyError: 2638L
```

**Comment by andygrunwald** [comment]
Hey @sduenas,

can you reproduce this error with the latest versions of RepositoryHandler and CVSAnaly?
I tried to reproduce it, but i wasnt successful:

```
cvsanaly2 -u root -d petals_cvsanaly --extensions=Metrics --metrics-all https://anonymous:anonymous@svn.petalslink.org/svnroot/trunk/product/dev/prod/petals/ 
Parsing log for https://anonymous:anonymous@svn.petalslink.org/svnroot/trunk/product/dev/prod/petals (svn)
Executing extensions
Executing extension FileTypes
Executing extension Metrics
...
```

**Comment by andygrunwald** [comment]
30 days no reply.
If @sduenas got the problem again please open a new ticket. Thx :)
