### ISSUE TITLE
Error while running CVSAnaly with opensuse kernel-source

### ISSUE THREAD

**Issue by athanrous** [MetricsGrimoire/CVSAnalY#31]
I face the following error while trying to analyse the kernel-source repository
[see git clone git://gitorious.org/opensuse/kernel-source.git] 

zoumpis@linux-sn3j:~/.cvsanaly2/cache> cvsanaly2 --db-user root --db-password root --db-database cvsanaly_kernel_sources /home/zoumpis/git/kernel-source/
Parsing log for /home/zoumpis/git/kernel-source/ (git)
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 504, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/cvsanaly2-2.1.0-py2.7.egg/pycvsanaly2/DBTempLog.py", line 131, in __writer
    cursor.executemany (statement ("INSERT into _temp_log (rev, date, object) values (?, ?, ?)", self.db.place_holder), commits)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 223, in executemany
    r = self._query('\n'.join([query[:p], ',\n'.join(q), query[e:]]))
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 316, in _query
    rowcount = self._do_query(q)
  File "/usr/lib64/python2.7/site-packages/MySQLdb/cursors.py", line 280, in _do_query
    db.query(q)
OperationalError: (2006, 'MySQL server has gone away')

FYI

zoumpis@linux-sn3j:~> cvsanaly2 -V
2.1.0

**Comment by andygrunwald** [comment]
Hey @athanrous,

thanks for your report.
Sadly i can not reproduce your error:

```
$ ./CVSAnalY.git/cvsanaly2 --db-user root  --db-database kernel kernel-source.git
Parsing log for kernel-source.git (git)
Warning: Detected empty branch 'openSUSE-13.1', it'll be ignored
Warning: Detected empty branch 'packaging', it'll be ignored
Warning: Detected empty branch 'scripts', it'll be ignored
Executing extensions
```

Did you try to raise the max_packet_size of your MySQL server? See here https://github.com/MetricsGrimoire/CVSAnalY#useful-settings

**Comment by athanrous** [comment]
Hey @andygrunwald 

Thanks for your tip. The problem is now solved.
