### ISSUE TITLE
Prob Parsing repository from MediaWiki

### ISSUE THREAD

**Issue by acs** [MetricsGrimoire/CVSAnalY#39]
acs@lenovix:/tmp$ git clone https://gerrit.wikimedia.org/r/p/mediawiki/extensions/cldr
acs@lenovix:~/devel/CVSAnalY$ ./cvsanaly2 -g -u root -p xxxx -d acs_cvsanaly_mediawiki_1598 /tmp/cldr/
BG: SELECT max(id) from tag_revisions
Parsing log for /tmp/cldr/ (git)
['git', 'log', '--all', '--topo-order', '--pretty=fuller', '--parents', '--name-status', '-M', '-C', '--decorate=full', 'origin']
DBG: Commit 5eeb30800653f70656414b4a4c472586686a5fce tagged as '2013.05'
Traceback (most recent call last):
  File "./cvsanaly2", line 37, in <module>
    retval = pycvsanaly2.main.main (sys.argv[1:])
  File "/home/acs/devel/CVSAnalY/pycvsanaly2/main.py", line 328, in main
    reader.start (new_line, (parser, writer))
  File "/home/acs/devel/CVSAnalY/pycvsanaly2/Log.py", line 92, in start
    self._read_from_repository (new_line_cb, user_data)
  File "/home/acs/devel/CVSAnalY/pycvsanaly2/Log.py", line 78, in _read_from_repository
    new_line_cb (line, user_data)
  File "/home/acs/devel/CVSAnalY/pycvsanaly2/main.py", line 320, in new_line
    parser.feed (line)
  File "/home/acs/devel/CVSAnalY/pycvsanaly2/Parser.py", line 56, in feed
    self._parse_line (line)
  File "/home/acs/devel/CVSAnalY/pycvsanaly2/GitParser.py", line 202, in _parse_line
    self.branch.set_tail (git_commit)
AttributeError: 'NoneType' object has no attribute 'set_tail'

**Comment by acs** [comment]
Fixed by 

https://github.com/MetricsGrimoire/CVSAnalY/commit/341e813eebc86e132e43ba5407f0bbc72f788956
