### ISSUE TITLE
Error with git version "1.8.4.rc3"

### ISSUE THREAD

**Issue by jgbarah** [MetricsGrimoire/CVSAnalY#47]
When running current (fresh from git repo) CVSAnalY with git version "1.8.4.rc3" (current in Debian testing) I get:

```
Parsing log for . (git)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/jgb/src/MetricsGrimoire/CVSAnalY/pycvsanaly2/Log.py", line 62, in _logreader
    repo.log (self.uri or repo.get_uri ())
  File "/home/jgb/src/MetricsGrimoire/RepositoryHandler/repositoryhandler/backends/git.py", line 259, in log
    major, minor, micro, extra = self._get_git_version()
  File "/home/jgb/src/MetricsGrimoire/RepositoryHandler/repositoryhandler/backends/git.py", line 107, in _get_git_version
    self.git_version = tuple([int(i) for i in version.split('.')])
ValueError: invalid literal for int() with base 10: 'rc3\n'
```

Running git --version I get:

```
git version 1.8.4.rc3
```

My guess is that CVSAnalY doesn't like characters as a part of the git version id...

**Comment by jgbarah** [comment]
Oooops. This is not a CVSAnaly bug. It was due to an old RepositoryHandler I had installed. I just upgraded it, and no problem at all. Sorry for the noise.

**Comment by andygrunwald** [comment]
Yep. This was fixed some days ago: https://github.com/MetricsGrimoire/RepositoryHandler/commit/f9e18ebf3cf87796d526b0db0dff8a2f246b7461
