### ISSUE TITLE
Content-Extension: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by andygrunwald** [MetricsGrimoire/CVSAnalY#79]
If i run CVSAnalY with the git repo of CVSAnalY with this config:

```
db_driver = 'mysql'
db_user = 'root'
db_password = None
db_hostname = 'localhost'

extensions = ['Content']
```

and command `./cvsanaly2 -d cvsanaly_before -f ./config .`

I got some errors:

```
./cvsanaly2 -d cvsanaly_before -f ./config .
Parsing log for . (git)
Warning: Detected empty branch 'travisci-readme', it'll be ignored
Warning: Detected empty branch 'pep8-pycvsanaly2', it'll be ignored
Warning: Detected empty branch 'travisci', it'll be ignored
Warning: Detected empty branch 'pep8-tests', it'll be ignored
Warning: Detected empty branch 'pep8-root', it'll be ignored
Warning: Detected empty branch 'libresoft-utils', it'll be ignored
Database looks empty, removing cache file /Users/andygrunwald/.cvsanaly2/cache/git@github.com:andygrunwald_CVSAnalY.git
Executing extensions
Executing extension FileTypes
Executing extension Content
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Volumes/HDD/Development/CVSAnalY.git/pycvsanaly2/extensions/Jobs.py", line 49, in _job_thread
    job.run(repo, repo_uri)
  File "/Volumes/HDD/Development/CVSAnalY.git/pycvsanaly2/extensions/Content.py", line 61, in run
    self.path = self.path.strip('/')
AttributeError: 'NoneType' object has no attribute 'strip'

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Volumes/HDD/Development/CVSAnalY.git/pycvsanaly2/extensions/Jobs.py", line 49, in _job_thread
    job.run(repo, repo_uri)
  File "/Volumes/HDD/Development/CVSAnalY.git/pycvsanaly2/extensions/Content.py", line 61, in run
    self.path = self.path.strip('/')
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by mniemela** [comment]
I'm probably stating the obvious, but self.path is None which causes the exception. Is this supposed to happen in any circumstances?
